### ISSUE TITLE
Handle arithmetic double negation

### ISSUE THREAD

**Issue by Semnodime** [ben-sb/javascript-deobfuscator#38] opened 2023-05-11 13:53 UTC
<strike>`0 - - 4` should optionally be refactored to `4`</strike>
`0 - - - - 4` should optionally be refactored to `4`

**Comment by ben-sb** [comment] 2023-05-11 21:15
This should already be handled, can you send details on your setup? Works as intended on the web version
<img width="1100" alt="Screenshot 2023-05-11 at 22 14 04" src="https://github.com/ben-sb/javascript-deobfuscator/assets/37311363/4e68e23a-859c-4ed9-a9e6-06cdfb953394">

**Comment by Semnodime** [comment] 2023-05-11 21:18
`0 - - - - 4` should optionally be refactored to `4`

**Comment by Semnodime** [comment] 2023-05-11 21:20
so goes for any arithmatic chain of `+` with `-` irrespective of its length.

**Comment by ben-sb** [comment] 2023-05-11 21:50
Should be fixed in latest commit

**Closed** 2023-05-12 17:50 UTC

**Comment by Semnodime** [comment] 2023-05-15 22:06
@ben-sb When will it go live in https://deobfuscate.io/ ?

**Comment by ben-sb** [comment] 2023-05-15 22:16
I updated the website at the same time as updating the repo so should have been live since then. Works for me with the example you sent, `0 - - - - 4`
